### ISSUE TITLE
Add "Learn Git Branching" to Git Resources section in docs

### ISSUE THREAD

**Issue by tesla809** [COVID-19-electronic-health-system/.github#15]
Could we add the following [resource to learn git branching](https://learngitbranching.js.org/?locale=en_US) to the [resources/git section](https://github.com/COVID-19-electronic-health-system/.github/blob/master/SUPPORT.md#git--github) of our docs?

**Comment by bcsaxon** [comment]
I could take this off yer hands.

**Comment by whoabuddy** [comment]
All yours, thank you!

**Comment by tesla809** [comment]
CONGRATS on your first PULL REQUEST @bcsaxon !!! WOOHOO!!!
