### ISSUE TITLE
[DOCS] Update Project Leads in SUPPORT.md

### ISSUE THREAD

**Issue by whoabuddy** [COVID-19-electronic-health-system/.github#16]
Looking at [the list here](https://github.com/COVID-19-electronic-health-system/.github/blob/master/SUPPORT.md#project-leads-and-contact-info) versus the table I created in  issue #9 (and the comments), we need to add:

Adham Abo Hasson (Front End Lead)
- Description: Front End
- Github @AdhamAH 
- Discord `Adham`

Austin Wu (Operations Lead)
- Description: Front End and Technical Operations
- Github @awu556 
- Discord `AWu`

**Comment by ngiangre** [comment]
Nick Giangreco (Analytics Lead)

Description: Data and Analytics lead
Github ngiangre
Discord NickG (Analytics Lead)
