### ISSUE TITLE
[BUG] Convert Giangre to Giangreco :)

### ISSUE THREAD

**Issue by ngiangre** [COVID-19-electronic-health-system/.github#22]
# ⚠️ IMPORTANT: Please fill out this template to give us as much information as possible to address the issue.

### Prerequisites

- [x] check this box if you have completed the following:
    - Reproduced the problem in QA
    - Reviewed the [contributing guidelines](https://github.com/COVID-19-electronic-health-system/.github/blob/master/CONTRIBUTING.md) and [support](https://github.com/COVID-19-electronic-health-system/.github/blob/master/SUPPORT.md) files
    - Reviewed the README file for the repository you are working in
    - Searched for relevant instructions [on our Discord server](https://discord.gg/pPERUuv)
    - Searched the issues of the repository you are working in to make sure one was not already filed

### Steps to Reproduce

1. 
2. 
3.

**Comment by whoabuddy** [comment]
Thanks for catching that! This should be fixed by #21 commit bf4cc8c once merged.

**Comment by whoabuddy** [comment]
Closing, fixed via #21
