### ISSUE TITLE
Update repository descriptions

### ISSUE THREAD

**Issue by whoabuddy** [COVID-19-electronic-health-system/.github#7]
The goal of this issue is to create a consistent naming convention for all repository descriptions, matching the layout in SUPPORT.md > CoronaTracker Resources > Repositories.

- [x] __[.github](https://github.com/COVID-19-electronic-health-system/.github):__ Community health files for the [@COVID-19-electronic-health-system](https://github.com/COVID-19-electronic-health-system) organization.

- [x] __[PanFLUte:](https://github.com/COVID-19-electronic-health-system/PanFLUte)__ An open source spirometer for everyone.

- [x] __[Coronalert:](https://github.com/COVID-19-electronic-health-system/Coronalert)__ CoronaTracker notification service

- [x] __[Corona-tracker:](https://github.com/COVID-19-electronic-health-system/Corona-tracker)__ CoronaTracker is an easy-to-use and accessible progressive web application that helps you monitor your wellness and stay informed during the COVID-19 crisis, designed by an open-source community invested in public health.

- Corona-tracker Now: ~~A web application promoting accurate COVID-19 guidelines and tracking user symptoms~~

- [ ] __[Coronalytics:](https://github.com/COVID-19-electronic-health-system/Coronalytics)__ CoronaTracker analytics service

- Coronalytics Now: _no description_

- [x] __[Coronadvise:](https://github.com/COVID-19-electronic-health-system/Coronadvise)__ CoronaTracker education service

- Coronadvise Now: ~~Our COVID-19 educational service~~

I wanted to run this by the team for input before making any changes, if this looks good to you, please comment and let me know!

**Comment by SomeMoosery** [comment]
So is this something done in this repo? Or in the individual repos? Because I have added README content in `Coronalert`, but don't know if I should move/replicate it here.

**Comment by whoabuddy** [comment]
It's even simpler than that! These are the descriptions that go right below the repos. (screenshot below)

![Screenshot_20200414-220146_Brave](https://user-images.githubusercontent.com/9038904/79300483-b7fc0900-7e9b-11ea-978d-8d15a6906618.jpg)

The issue was just an easy way to track that we discussed and agreed on the change.

**Comment by whoabuddy** [comment]
I went ahead and updated the description for each repository, this one is complete!
